version: '3.1'

services:
  postgres:
    image: postgres:16.2-alpine3.19
    env_file:
      - .env
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
      - ./postgres-initdb/:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"

