version: '3.1'

services:
  postgres:
    image: postgres:16.2-alpine3.19
    env_file:
      - .env
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
      - ./certs/server:/etc/certs
      - ./server.conf:/etc/postgresql.conf
      - ./pg_hba.conf:/etc/pg_hba.conf
    command: -c 'config_file=/etc/postgresql/postgresql.conf'
    ports:
      - "5432:5432"

