version: '3.1'

services:
  postgres:
    image: postgres:16.2-alpine3.19
    env_file:
      - .env
    volumes:
      - ./certs/server:/var/lib/postgresql/certs
      - ./server.conf:/etc/postgresql/postgresql.conf
      - ./pg_hba.conf:/var/lib/postgresql/data/pg_hba.conf
      - postgres_data:/var/lib/postgresql/data
    command: -c 'config_file=/etc/postgresql/postgresql.conf'
    ports:
      - "5432:5432"

volumes:
  postgres_data:
